# Site settings
title: Diseño centrado en el usuario
email:
description: Este sitio ofrece las buenas prácticas de desarrollo Web orientadas a la accesibilidad y la usabilidad.
baseurl: "/usayaccess/" # the subpath of your site, e.g. /blog/
url: "http://dcuproject.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
collections:
  html5:
    output: true
    permalink: /html5/:path/
  css3:
    output: true
    permalink: /css3/:path/
